name: account_ledger_windows
description: Account Ledger Windows Desktop App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-170.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  motion_toast: ^2.6.8
  await_sleep: ^1.0.1
  account_ledger_library:
    path: account_ledger_library_dart
  integer: ^2.0.1
  audio_in_app: ^2.1.1
  dropdown_search: ^5.0.6
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.2
  build_runner: ^2.4.6
  analyzer: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/button.wav
