name: 'Upload Build Artifact'
description: 'Uploads the build artifact to GitHub Actions.'
inputs:
  artifact_name:
    description: 'The name of the artifact.'
    required: true
  artifact_path:
    description: 'The path to the artifact.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}
